from django.contrib import admin
from django.urls import path,include
from project import views


urlpatterns = [
    path('',views.index,name="index"),
    #  path('features',views.features,name="features"),
    #  path("pricing",views.pricing,name="pricing"),
    path("login",views.loginUser,name="login"),
    path("home",views.home,name="home"),
    path("logout",views.logoutUser,name="logout"),
    path("teacheradd",views.teacheradd,name="teacheradd"),
    path("room_management", views.room_management, name="roommanage"),
    path("staff_management", views.staff_management, name="staffmanage"),
    path("subject_management", views.subject_management, name="submanage"),
    path("roomallot_management",views.roomallot_management,name="roomallot_management"),
    path("exam_management", views.exam_management, name="exammanage"),
    path("roomadd",views.roomadd,name="roomadd"),
    path("roomdisplay",views.roomdisplay,name="roomdisplay"),
    path("teacherdisplay",views.teacherdisplay,name="teacherdisplay"),
    path("roomedit",views.roomedit,name="roomedit"),
    path("teacheredit",views.teacheredit,name="teacheredit"),
    path("roomupdate/<int:roomno>",views.roomupdate,name="roomupdate"),
    path("roomdelete/<int:roomno>",views.roomdelete,name="roomdelete"),
    path("teacherupdate/<int:staff_id>",views.teacherupdate,name="teacherupdate"),
    path("teacherdelete/<int:staff_id>",views.teacherdelete,name="teacherdelete"),
    path("subjectadd",views.subjectadd,name="subjectadd"),
    path("subjectupdate/<int:subid>",views.subjectupdate,name="subjectupdate"),
    path("subjectdelete/<int:subid>",views.subjectdelete,name="subjectdelete"),
    path("subjectedit",views.subjectedit,name="subjectedit"),
    path("subjectdisplay",views.subjectdisplay,name="subjectdisplay"),
    path("timetableinsertion",views.timetableinsertion,name="timetableinsertion"),
    path("addallotment",views.addallotment,name="addallotment"),
    path("autoseat",views.autoseat,name="autoseat"),
    path("pdf_to_text",views.pdf_to_text,name="pdf_to_text"),
    # path("refresh",views.refresh,name='refresh'),
    path("manualseat",views.manualseat,name="manualseat"),
    # path("generate_id/",views.generate_id,name="generate_id"),
    path("viewall",views.viewall,name="viewall"),
    path("userhome",views.userhome,name="userhome"),
    path("profile",views.profile,name="profile"),
    path("profilesaved/<int:staff_id>",views.profilesaved,name="profilesaved"),
    path("autoinsert",views.autoinsert,name="autoinsert"),
    path("changepassword",views.changepassword,name="changepassword"),
    path("manualinsert",views.manualinsert,name="manualinsert"),
]
