# Generated by Django 4.1.7 on 2023-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatallotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=60)),
                ('tname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seatallotment',
            },
        ),
    ]
