# Generated by Django 4.1.7 on 2023-04-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_seatallotment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seatallotment',
        ),
    ]
