# Generated by Django 4.1.7 on 2023-04-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_autoseatadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='address',
            new_name='phone',
        ),
    ]
