# Generated by Django 4.1.7 on 2023-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_address_teachers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(max_length=10)),
                ('subcode', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='table1',
        ),
    ]
