# Generated by Django 4.1.7 on 2023-05-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_subject_delete_table1'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_allot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('teachername', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('passwrd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10)),
                ('sid', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(verbose_name='')),
                ('exam_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='autoseatadd',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AddField(
            model_name='subject',
            name='subname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stream',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
