# Generated by Django 4.1.7 on 2023-05-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_room_allot_staff_time_table_delete_autoseatadd_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_allot',
            new_name='room_allotment',
        ),
    ]
