# Generated by Django 4.1.7 on 2023-05-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rallot_delete_room_allotment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rallot',
            new_name='room_allotment',
        ),
    ]
