# Generated by Django 4.1.7 on 2023-05-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_rallot_room_allotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
