# Generated by Django 4.1.7 on 2023-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_subject_subid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
