# Generated by Django 4.1.7 on 2023-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_subject_subid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
