# Generated by Django 4.1.7 on 2023-05-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_time_table_date_time_time_table_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_allotment',
            name='edate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='room_allotment',
            name='etime',
            field=models.TimeField(default=None),
        ),
    ]
