# Generated by Django 4.1.7 on 2023-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_room_allotment_examdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_allotment',
            name='edate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='room_allotment',
            name='etime',
            field=models.TimeField(default=None),
        ),
    ]
