# Generated by Django 4.1.7 on 2023-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_room_allotment_edate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_allotment',
            name='edate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room_allotment',
            name='etime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='exam_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='exam_time',
            field=models.CharField(max_length=50),
        ),
    ]
