# Generated by Django 4.1.7 on 2023-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_room_allotment_edate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_allotment',
            name='edate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
