# Generated by Django 4.1.7 on 2023-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_room_allotment_edate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_allotment',
            name='student_allot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_cap',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_table',
            name='sub_student',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
