# Generated by Django 4.1.7 on 2023-06-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_rename_student_allot_room_allotment_student_alloted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_cap',
        ),
    ]
