# Generated by Django 4.1.7 on 2023-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_remove_rooms_room_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_allotment',
            name='exam_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
