# Generated by Django 4.1.7 on 2023-06-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_room_allotment_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_allotment',
            name='exam_date',
        ),
    ]
