# Generated by Django 4.1.7 on 2023-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_remove_room_allotment_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_allotment',
            name='e_date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
