# Generated by Django 4.1.7 on 2023-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_room_allotment_e_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='exam_date',
            field=models.CharField(max_length=20),
        ),
    ]
