# Generated by Django 4.1.7 on 2023-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_remove_room_allotment_e_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_allotment',
            name='room_exam_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_table',
            name='exam_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
