# Generated by Django 4.1.7 on 2023-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_rename_tid_room_allotment_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='time_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='tid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
