# Generated by Django 4.1.7 on 2023-06-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_remove_time_table_exam_time_time_table_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subid',
            field=models.IntegerField(),
        ),
    ]
